//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gui.rc
//
#define IDCANCEL2                       3
#define IDD_ABOUTBOX                    100
#define IDD_SELECT_GAME                 101
#define IDR_MAINFRAME                   128
#define IDR_GUITYPE                     129
#define IDS_FILE_OPEN_FILTER            129
#define IDD_PROMOTION                   132
#define IDD_SEARCH_GROUP                133
#define IDD_FIXED_PLY                   134
#define IDD_FIXED_TIME                  135
#define IDD_INCREMENTAL                 136
#define IDD_TOURNAMENT                  137
#define IDD_VAR1_EDIT                   138
#define IDD_VAR2_EDIT                   139
#define IDD_SEARCH_LIMITS_LABEL1        140
#define IDD_SEARCH_LIMITS_LABEL2        141
#define IDD_SEARCH_LIMITS               142
#define IDD_FIXED_DEPTH                 142
#define IDD_SHOW_GAME_MOVES             143
#define IDD_PREFERENCES                 144
#define IDD_FONT_SELECT                 145
#define IDD_APPEARANCE                  145
#define IDD_COLORS                      147
#define IDR_WP                          150
#define IDR_WN                          151
#define IDR_WB                          152
#define IDR_WR                          153
#define IDR_WQ                          154
#define IDR_WK                          155
#define IDR_BP                          156
#define IDR_BN                          157
#define IDR_BB                          158
#define IDR_BR                          159
#define IDR_BQ                          160
#define IDR_BK                          161
#define IDR_WN32                        163
#define IDR_WB32                        164
#define IDR_BN32                        165
#define IDC_QUEEN                       1001
#define IDC_ROOK                        1002
#define IDC_BISHOP                      1003
#define IDC_KNIGHT                      1004
#define IDC_GAMELIST                    1005
#define IDC_GAME_LIST                   1006
#define IDC_BEEP_AFTER_MOVE_CHECK       1007
#define IDC_FORCE_MONO                  1008
#define IDC_FONT_COMBO                  1009
#define IDC_FONT_PREVIEW                1010
#define IDC_BEEP_ON_ERROR_CHECK         1011
#define IDC_BOARD_SIZE_COMBO            1012
#define IDC_PONDER_CHECK                1013
#define IDC_SHOW_COORD_CHECK            1014
#define IDC_CAN_RESIGN_CHECK            1015
#define IDC_HASH_SIZE_EDIT              1016
#define IDC_HASH_SIZE_SPIN              1017
#define IDC_LIGHTSQUARES                1018
#define IDC_DARKSQUARES                 1019
#define IDC_LIGHTCOLOR                  1020
#define IDC_DARKCOLOR                   1021
#define IDC_CHOOSELIGHT                 1022
#define IDC_CHOOSEDARK                  1023
#define IDC_AUTO_SIZE                   1064
#define IDC_SIZE_LABEL                  1074
#define IDC_HYPERLINK                   1075
#define IDC_CORES_LABEL                 1076
#define IDC_CORES_EDIT                  1077
#define IDC_CORES_SPIN                  1078
#define IDC_STRENGTH_SPIN               1079
#define IDD_STRENGTH_LABEL              1080
#define IDC_STRENGTH_EDIT               1081
#define IDC_POSITION_LEARNING_CHECK     1082
#define IDC_TB_PATH_LABEL               1083
#define IDC_TB_PATH_EDIT                1084
#define IDD_BOOK_VARIETY_LABEL          1085
#define IDC_BOOK_VARIETY_EDIT           1086
#define IDC_BOOK_VARIETY_SPIN           1087
#define ID_MAKEUSERMOVE                 32790
#define ID_LOSSONTIME                   32791
#define ID_ENGINE_REPLY                 32792
#define ID_VIEW_PV                      32793
#define ID_BROWSE_NEXTGAME              32794
#define ID_BROWSE_PREVIOUSGAME          32795
#define ID_BROWSE_SELECTGAME            32796
#define ID_RESIZE                       32797
#define ID_TAKEBACK_MOVE                32798
#define ID_MOVE_FORWARD                 32799
#define ID_FORWARD                      32800
#define ID_GAME_BEGINNINGOFGAME         32801
#define ID_BEGIN_GAME                   32802
#define ID_GAME_ENDOFGAME               32803
#define ID_HINT                         32804
#define ID_COMPUTE                      32805
#define ID_RESET                        32806
#define ID_CLOCK_RESET                  32806
#define ID_EDIT_COPY_POSITION           32808
#define ID_EDIT_COPY_GAME               32809
#define ID_OPTIONS_SEARCH_LIMITS        32810
#define ID_OPTIONS_PREFERENCES          32811
#define ID_BUTTON32812                  32812
#define ID_PAUSE                        32813
#define ID_CLOCK_PAUSE                  32813
#define ID_GAME_ROTATE_BOARD            32814
#define ID_GAME_SHOW_MOVES              32815
#define ID_PLAYWHITE                    32816
#define ID_OPTIONS_CHESSFONT            32817
#define ID_HELP_SEARCH                  32818
#define ID_OPTIONS_APPEARANCE           32819
#define ID_BOARD_COLORS                 32820
#define ID_ABOUTDIALOG                  32821
#define IDS_READY                       32900
#define IDS_CANT_OPEN                   32901
#define IDS_UNKNOWN_FILE_TYPE           32902
#define IDS_INVALID_BOARD               32903
#define IDS_INVALID_FEN                 32905
#define IDS_ILLEGAL_MOVE                32906
#define IDS_UNREC_TEXT                  32907
#define IDS_LETTER_COORDS               32908
#define IDS_NUMBER_COORDS               32909
#define IDS_SEARCHING                   32910
#define ID_INDICATOR_ECO                32911
#define IDS_ENGINE_STARTUP              32912
#define IDS_ENGINE_NOT_FOUND            32913
#define IDS_ENGINE_ACCESS_DENIED        32914
#define IDS_WHITE                       32915
#define IDS_BLACK                       32916
#define ID_INDICATOR_PLYLABEL           61447
#define ID_INDICATOR_PLY                61448
#define ID_INDICATOR_SCORELABEL         61449
#define ID_INDICATOR_SCORE              61450
#define ID_INDICATOR_NODELABEL          61451
#define ID_INDICATOR_NODES              61452
#define ID_INDICATOR_PVLABEL            61453
#define ID_INDICATOR_PV                 61454

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        163
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
